In [8]:
import pandas as pd
import numpy as np

In [9]:
a = np.array([1, 2, 3])
a, type(a)

(array([1, 2, 3]), numpy.ndarray)

In [10]:
Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})
Hut_Paradise_DF

,1.Rent,2.Area,3.Rooms,4.Floor,5.Demo two weeks,6.Liv.Area
0,65,50,3,5,8,37
1,70,52,2,12,4,40
2,120,80,1,10,5,65
3,35,33,1,3,10,20
4,40,33,1,6,20,16
5,50,44,2,13,12,35
6,100,80,4,8,5,60
7,90,65,3,21,1,50
8,85,65,2,5,10,40


In [11]:
A = Hut_Paradise_DF.values
A

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]])

In [23]:
header = {
    'rent': 0,
    'area': 1,
    'rooms': 2,
    'floor': 3,
    'demo_2w': 4,
    'liv_area': 5,
}

Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). 

In [16]:
A[5 -1]

array([40, 33,  1,  6, 20, 16])

Найдите вектор этажей всех квартир.

In [19]:
rent = A[:, header['floor']]
rent

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

Вычислите вектор нежилой площади. 

In [20]:
nonliv_area = A[:, header['area']] - A[:, header['liv_area']]
nonliv_area

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [28]:
view_time = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20,])

In [29]:
time_2w = view_time * A[:, header['demo_2w']]
np.sum(time_2w)

1348

In [33]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

Составьте линейную комбинацию векторов 'v' и 'w' с коэффициентами 2 и -3.

In [42]:
x = 2*v + -3*w
x

array([-3, 14,  3,  4,  2])

Будет ли эта комбинация ортогональна вектору 'u'?


In [46]:
print("Yes" if x@u == 0 else "No")

Yes
