In [34]:
import pandas as pd
import numpy as np

In [9]:
a = np.array([1, 2, 3])
a, type(a)

(array([1, 2, 3]), numpy.ndarray)

In [10]:
Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})
Hut_Paradise_DF

,1.Rent,2.Area,3.Rooms,4.Floor,5.Demo two weeks,6.Liv.Area
0,65,50,3,5,8,37
1,70,52,2,12,4,40
2,120,80,1,10,5,65
3,35,33,1,3,10,20
4,40,33,1,6,20,16
5,50,44,2,13,12,35
6,100,80,4,8,5,60
7,90,65,3,21,1,50
8,85,65,2,5,10,40


In [11]:
A = Hut_Paradise_DF.values
A

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]])

In [23]:
header = {
    'rent': 0,
    'area': 1,
    'rooms': 2,
    'floor': 3,
    'demo_2w': 4,
    'liv_area': 5,
}

Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). 

In [16]:
A[5 -1]

array([40, 33,  1,  6, 20, 16])

Найдите вектор этажей всех квартир.

In [19]:
rent = A[:, header['floor']]
rent

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

Вычислите вектор нежилой площади. 

In [20]:
nonliv_area = A[:, header['area']] - A[:, header['liv_area']]
nonliv_area

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [28]:
view_time = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20,])

In [29]:
time_2w = view_time * A[:, header['demo_2w']]
np.sum(time_2w)

1348

In [33]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

Составьте линейную комбинацию векторов 'v' и 'w' с коэффициентами 2 и -3.

In [42]:
x = 2*v + -3*w
x

array([-3, 14,  3,  4,  2])

Будет ли эта комбинация ортогональна вектору 'u'?


In [46]:
print("Yes" if x@u == 0 else "No")

Yes


<b>3/6</b>   Практика: базовые действия над матрицами

In [2]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [3]:
m_inc = np.array([
    [100,220,140],
    [150,200,130],
    [90,80,100],
]).T

In [4]:
headers = {
    'husband': 0,
    'wife': 1,
    'mother_in_law': 2,
}

In [6]:
headers, m_inc

({'husband': 0, 'wife': 1, 'mother_in_law': 2},
 array([[100, 150,  90],
        [220, 200,  80],
        [140, 130, 100]]))

In [7]:
np.diag(m_inc)

array([100, 200, 100])

In [8]:
m_cons = np.array([
    [50,50,60],
    [100,80,140],
    [100,20,140],
]).T

In [9]:
m_cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [10]:
np.diag(m_cons)

array([ 50,  80, 140])

In [11]:
m_inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [12]:
m_inc_after_tax = m_inc * (100 - 13)/100

In [13]:
m_inc_after_tax

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [14]:
m_inc_after_tax[0]

array([ 87. , 130.5,  78.3])

In [15]:
m_profit = m_inc_after_tax - m_cons

In [16]:
m_profit

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [17]:
m_profit[3 -1]

array([ 61.8, -26.9, -53. ])

<b>4/6</b>   Практика: матричное умножение

In [19]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
A, x, type(A), type(x)

(array([[ 5, -1,  3,  1,  2],
        [-2,  8,  5, -1,  1]]),
 array([1, 2, 3, 4, 5]),
 numpy.ndarray,
 numpy.ndarray)

In [20]:
A@x

array([26, 30])

In [23]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
B, A, np.shape(B), np.shape(A)

(array([[ 1, -1,  0,  1,  1],
        [-2,  0,  2, -1,  1]]),
 array([[1, 9, 8, 5],
        [3, 6, 3, 2],
        [3, 3, 3, 3],
        [0, 2, 5, 9],
        [4, 4, 1, 2]]),
 (2, 5),
 (5, 4))

In [25]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [27]:
x = np.array([ 1, 2, 1, 0, 4])
y = np.array([ 2, 1,-1, 1, 0])
z = np.array([-1, 1,-1, 0, 0])

x, y, z

(array([1, 2, 1, 0, 4]),
 array([ 2,  1, -1,  1,  0]),
 array([-1,  1, -1,  0,  0]))

In [28]:
A = np.array([x, y, z])
A, np.shape(A)

(array([[ 1,  2,  1,  0,  4],
        [ 2,  1, -1,  1,  0],
        [-1,  1, -1,  0,  0]]),
 (3, 5))

In [31]:
# матрица Грама (скалярное произведение строк)
A@A.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [30]:
# матрица Грама (скалярное произведение столбцов)
A.T@A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [35]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [39]:
Count_DF, Price_DF

(       Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
 Аня                 10                5           12       15    10
 Борис                2               21            3       25     6
 Вика                12               12            0       30     4
 Галя                 4                8           18       14     5
 Дима                 6               25           27       25    18
 Егор                10                3            2       17    12
 Женя                22                1            4       25    20
 Юра                  7                0           31       31    28,
        Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
 Аня                2.0              1.5          1.0      0.8   1.0
 Борис              1.8              2.5          1.0      1.0   1.0
 Вика               2.0              2.0          0.0      0.5   2.0
 Галя               1.8              1.2          2.8      0.8   2.0
 Дима               2.5          

In [45]:
m_count = Count_DF.values
m_price = Price_DF.values
m_count, m_price

(array([[10,  5, 12, 15, 10],
        [ 2, 21,  3, 25,  6],
        [12, 12,  0, 30,  4],
        [ 4,  8, 18, 14,  5],
        [ 6, 25, 27, 25, 18],
        [10,  3,  2, 17, 12],
        [22,  1,  4, 25, 20],
        [ 7,  0, 31, 31, 28]]),
 array([[2. , 1.5, 1. , 0.8, 1. ],
        [1.8, 2.5, 1. , 1. , 1. ],
        [2. , 2. , 0. , 0.5, 2. ],
        [1.8, 1.2, 2.8, 0.8, 2. ],
        [2.5, 3.5, 2. , 1. , 1.5],
        [5. , 5. , 3. , 2. , 2.5],
        [1.1, 1. , 1.5, 0.5, 1.7],
        [4.5, 4. , 2.5, 1. , 2. ]]))

In [44]:
# вектор комиссий
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
com

array([0.2, 0.2, 0.3, 0.1, 0.1])

In [47]:
m_income = m_count * m_price
m_income

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [52]:
m_com = m_income * com
m_com

array([[ 4.  ,  1.5 ,  3.6 ,  1.2 ,  1.  ],
       [ 0.72, 10.5 ,  0.9 ,  2.5 ,  0.6 ],
       [ 4.8 ,  4.8 ,  0.  ,  1.5 ,  0.8 ],
       [ 1.44,  1.92, 15.12,  1.12,  1.  ],
       [ 3.  , 17.5 , 16.2 ,  2.5 ,  2.7 ],
       [10.  ,  3.  ,  1.8 ,  3.4 ,  3.  ],
       [ 4.84,  0.2 ,  1.8 ,  1.25,  3.4 ],
       [ 6.3 ,  0.  , 23.25,  3.1 ,  5.6 ]])

In [53]:
v_com = m_income @ com
v_com

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [58]:
# сумма по столбцам
np.sum(m_com, axis=0)

array([35.1 , 39.42, 62.67, 16.57, 18.1 ])

In [59]:
# сумма по строкам
np.sum(m_com, axis=1)

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [60]:
np.sum(m_com)

171.86

In [62]:
m_profit = m_income - m_com
m_profit

array([[16.  ,  6.  ,  8.4 , 10.8 ,  9.  ],
       [ 2.88, 42.  ,  2.1 , 22.5 ,  5.4 ],
       [19.2 , 19.2 ,  0.  , 13.5 ,  7.2 ],
       [ 5.76,  7.68, 35.28, 10.08,  9.  ],
       [12.  , 70.  , 37.8 , 22.5 , 24.3 ],
       [40.  , 12.  ,  4.2 , 30.6 , 27.  ],
       [19.36,  0.8 ,  4.2 , 11.25, 30.6 ],
       [25.2 ,  0.  , 54.25, 27.9 , 50.4 ]])

In [64]:
np.sum(m_profit, axis=1)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

<b>5/6</b>   Практика: обратная матрица, определитель, ранг

In [1]:
import numpy as np

In [9]:
B = np.array([[2, 5], [1, 3]])
B

array([[2, 5],
       [1, 3]])

In [10]:
B_inv = np.linalg.inv(B).T
B_inv

array([[ 3., -1.],
       [-5.,  2.]])

In [17]:
import numpy as np

# Создаем матрицу
A = np.array([[1, 4, 13], [3, -4, 7], [5, 9, 12]])

# Вычисляем собственные числа
eigenvalues = np.linalg.eigvals(A)

print("Собственные числа матрицы A:")
print(eigenvalues)
a, b, c = eigenvalues
print(round(a), round(b), round(c))

Собственные числа матрицы A:
[19.52189628 -3.75422737 -6.76766891]
20 -4 -7


In [18]:
A = np.array([[1, 9, 4], [9, 4, 7],[4, 7, 12]])
A

array([[ 1,  9,  4],
       [ 9,  4,  7],
       [ 4,  7, 12]])

In [20]:
A.T

array([[ 1,  9,  4],
       [ 9,  4,  7],
       [ 4,  7, 12]])

In [21]:
A.T @ A

array([[ 98,  73, 115],
       [ 73, 146, 148],
       [115, 148, 209]])

In [22]:
# Вычисляем собственные числа
eigenvalues = np.linalg.eigvals(A.T @ A)

print("Собственные числа матрицы A:")
print(eigenvalues)
a, b, c = eigenvalues
print(round(a), round(b), round(c))

Собственные числа матрицы A:
[391.37004987  45.77088847  15.85906166]
391 46 16


In [5]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
A

array([[ 8,  6, 11],
       [ 7,  5,  9],
       [ 6, 10,  6]])

In [7]:
np.linalg.matrix_rank(A)

3

In [9]:
A_inv = np.linalg.inv(A)
A_inv

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [5]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

m_v = np.array([v1, v2, v3, v4]).T
m_v

array([[ 9,  2,  4,  3],
       [10,  0,  0, -4],
       [ 7,  5,  0,  3],
       [ 7,  1,  4, -1],
       [ 9,  4,  1, -4]])

In [7]:
np.linalg.matrix_rank(m_v)

4

In [9]:
m_v.T @ m_v

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [15]:
round(np.linalg.det(m_v.T @ m_v), 0)

3716648.0

In [19]:
np.linalg.matrix_rank(m_v.T @ m_v)

4

In [21]:
np.linalg.inv(m_v.T @ m_v)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [25]:
round(np.linalg.inv(m_v.T @ m_v)[3 -1, 1 -1], 3) # третья строка, первый столец

-0.026