In [12]:
import numpy as np

In [13]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [14]:
A

array([[ 8, 11, 10],
       [ 7,  7,  5],
       [ 5,  7,  6]])

In [15]:
B

array([[ 3,  0,  1],
       [ 1,  3, -1],
       [ 3,  0,  0]])

In [16]:
# Поэлементное умножение
A*B

array([[24,  0, 10],
       [ 7, 21, -5],
       [15,  0,  0]])

In [17]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[65 33 -3]
 [43 21  0]
 [40 21 -2]]


In [18]:
# Матричное умножение
np.dot(A,B)

array([[65, 33, -3],
       [43, 21,  0],
       [40, 21, -2]])

In [19]:
# Матричное умножение
A@B

array([[65, 33, -3],
       [43, 21,  0],
       [40, 21, -2]])

In [20]:
# Порядок умножения AB != BA
B@A

array([[29, 40, 36],
       [24, 25, 19],
       [24, 33, 30]])

In [22]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 9  7  8  7 10]
 [ 6 11  7  6  7]
 [11 10  5  7  8]]
B:
 [[ 0  1]
 [ 0  1]
 [-2  3]
 [-1  0]
 [ 3  0]]


In [23]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[ 7, 40],
       [ 1, 38],
       [ 7, 36]])

In [24]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [25]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [26]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-4 -4  2 -4]
 [-3 -4 -4  2]
 [ 3  3 -3 -4]
 [-1 -2 -3 -4]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-4 -8  0  4]
 [-3 -8  0 -2]
 [ 3  6  0  4]
 [-1 -4  0  4]]
DA:
 [[-4 -4  2 -4]
 [-6 -8 -8  4]
 [ 0  0  0  0]
 [ 1  2  3  4]]


In [27]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [28]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [29]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [30]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [31]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [32]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])